/*
 * Copyright (c) 2020 by The metal-stack Authors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/onmetal/k8s-machines/pkg/apis/machines/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// BaseBoardManagementControllerInfoLister helps list BaseBoardManagementControllerInfos.
type BaseBoardManagementControllerInfoLister interface {
	// List lists all BaseBoardManagementControllerInfos in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.BaseBoardManagementControllerInfo, err error)
	// BaseBoardManagementControllerInfos returns an object that can list and get BaseBoardManagementControllerInfos.
	BaseBoardManagementControllerInfos(namespace string) BaseBoardManagementControllerInfoNamespaceLister
	BaseBoardManagementControllerInfoListerExpansion
}

// baseBoardManagementControllerInfoLister implements the BaseBoardManagementControllerInfoLister interface.
type baseBoardManagementControllerInfoLister struct {
	indexer cache.Indexer
}

// NewBaseBoardManagementControllerInfoLister returns a new BaseBoardManagementControllerInfoLister.
func NewBaseBoardManagementControllerInfoLister(indexer cache.Indexer) BaseBoardManagementControllerInfoLister {
	return &baseBoardManagementControllerInfoLister{indexer: indexer}
}

// List lists all BaseBoardManagementControllerInfos in the indexer.
func (s *baseBoardManagementControllerInfoLister) List(selector labels.Selector) (ret []*v1alpha1.BaseBoardManagementControllerInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BaseBoardManagementControllerInfo))
	})
	return ret, err
}

// BaseBoardManagementControllerInfos returns an object that can list and get BaseBoardManagementControllerInfos.
func (s *baseBoardManagementControllerInfoLister) BaseBoardManagementControllerInfos(namespace string) BaseBoardManagementControllerInfoNamespaceLister {
	return baseBoardManagementControllerInfoNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// BaseBoardManagementControllerInfoNamespaceLister helps list and get BaseBoardManagementControllerInfos.
type BaseBoardManagementControllerInfoNamespaceLister interface {
	// List lists all BaseBoardManagementControllerInfos in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.BaseBoardManagementControllerInfo, err error)
	// Get retrieves the BaseBoardManagementControllerInfo from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.BaseBoardManagementControllerInfo, error)
	BaseBoardManagementControllerInfoNamespaceListerExpansion
}

// baseBoardManagementControllerInfoNamespaceLister implements the BaseBoardManagementControllerInfoNamespaceLister
// interface.
type baseBoardManagementControllerInfoNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all BaseBoardManagementControllerInfos in the indexer for a given namespace.
func (s baseBoardManagementControllerInfoNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.BaseBoardManagementControllerInfo, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.BaseBoardManagementControllerInfo))
	})
	return ret, err
}

// Get retrieves the BaseBoardManagementControllerInfo from the indexer for a given namespace and name.
func (s baseBoardManagementControllerInfoNamespaceLister) Get(name string) (*v1alpha1.BaseBoardManagementControllerInfo, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("baseboardmanagementcontrollerinfo"), name)
	}
	return obj.(*v1alpha1.BaseBoardManagementControllerInfo), nil
}
