/*
 * Copyright (c) 2020 by The metal-stack Authors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/onmetal/k8s-machines/pkg/apis/machines/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineInfoLister helps list MachineInfos.
type MachineInfoLister interface {
	// List lists all MachineInfos in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error)
	// MachineInfos returns an object that can list and get MachineInfos.
	MachineInfos(namespace string) MachineInfoNamespaceLister
	MachineInfoListerExpansion
}

// machineInfoLister implements the MachineInfoLister interface.
type machineInfoLister struct {
	indexer cache.Indexer
}

// NewMachineInfoLister returns a new MachineInfoLister.
func NewMachineInfoLister(indexer cache.Indexer) MachineInfoLister {
	return &machineInfoLister{indexer: indexer}
}

// List lists all MachineInfos in the indexer.
func (s *machineInfoLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfo))
	})
	return ret, err
}

// MachineInfos returns an object that can list and get MachineInfos.
func (s *machineInfoLister) MachineInfos(namespace string) MachineInfoNamespaceLister {
	return machineInfoNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MachineInfoNamespaceLister helps list and get MachineInfos.
type MachineInfoNamespaceLister interface {
	// List lists all MachineInfos in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error)
	// Get retrieves the MachineInfo from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.MachineInfo, error)
	MachineInfoNamespaceListerExpansion
}

// machineInfoNamespaceLister implements the MachineInfoNamespaceLister
// interface.
type machineInfoNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MachineInfos in the indexer for a given namespace.
func (s machineInfoNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MachineInfo, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineInfo))
	})
	return ret, err
}

// Get retrieves the MachineInfo from the indexer for a given namespace and name.
func (s machineInfoNamespaceLister) Get(name string) (*v1alpha1.MachineInfo, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("machineinfo"), name)
	}
	return obj.(*v1alpha1.MachineInfo), nil
}
