/*
 * Copyright (c) 2020 by The metal-stack Authors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/onmetal/k8s-machines/pkg/apis/machines/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// MachineTypeLister helps list MachineTypes.
type MachineTypeLister interface {
	// List lists all MachineTypes in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.MachineType, err error)
	// MachineTypes returns an object that can list and get MachineTypes.
	MachineTypes(namespace string) MachineTypeNamespaceLister
	MachineTypeListerExpansion
}

// machineTypeLister implements the MachineTypeLister interface.
type machineTypeLister struct {
	indexer cache.Indexer
}

// NewMachineTypeLister returns a new MachineTypeLister.
func NewMachineTypeLister(indexer cache.Indexer) MachineTypeLister {
	return &machineTypeLister{indexer: indexer}
}

// List lists all MachineTypes in the indexer.
func (s *machineTypeLister) List(selector labels.Selector) (ret []*v1alpha1.MachineType, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineType))
	})
	return ret, err
}

// MachineTypes returns an object that can list and get MachineTypes.
func (s *machineTypeLister) MachineTypes(namespace string) MachineTypeNamespaceLister {
	return machineTypeNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// MachineTypeNamespaceLister helps list and get MachineTypes.
type MachineTypeNamespaceLister interface {
	// List lists all MachineTypes in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.MachineType, err error)
	// Get retrieves the MachineType from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.MachineType, error)
	MachineTypeNamespaceListerExpansion
}

// machineTypeNamespaceLister implements the MachineTypeNamespaceLister
// interface.
type machineTypeNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all MachineTypes in the indexer for a given namespace.
func (s machineTypeNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.MachineType, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.MachineType))
	})
	return ret, err
}

// Get retrieves the MachineType from the indexer for a given namespace and name.
func (s machineTypeNamespaceLister) Get(name string) (*v1alpha1.MachineType, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("machinetype"), name)
	}
	return obj.(*v1alpha1.MachineType), nil
}
