/*
 * Copyright (c) 2020 by The metal-stack Authors.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/onmetal/k8s-machines/pkg/apis/machines/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMachineTypes implements MachineTypeInterface
type FakeMachineTypes struct {
	Fake *FakeMachinesV1alpha1
	ns   string
}

var machinetypesResource = schema.GroupVersionResource{Group: "machines.onmetal.de", Version: "v1alpha1", Resource: "machinetypes"}

var machinetypesKind = schema.GroupVersionKind{Group: "machines.onmetal.de", Version: "v1alpha1", Kind: "MachineType"}

// Get takes name of the machineType, and returns the corresponding machineType object, and an error if there is any.
func (c *FakeMachineTypes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.MachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(machinetypesResource, c.ns, name), &v1alpha1.MachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineType), err
}

// List takes label and field selectors, and returns the list of MachineTypes that match those selectors.
func (c *FakeMachineTypes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.MachineTypeList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(machinetypesResource, machinetypesKind, c.ns, opts), &v1alpha1.MachineTypeList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MachineTypeList{ListMeta: obj.(*v1alpha1.MachineTypeList).ListMeta}
	for _, item := range obj.(*v1alpha1.MachineTypeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested machineTypes.
func (c *FakeMachineTypes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(machinetypesResource, c.ns, opts))

}

// Create takes the representation of a machineType and creates it.  Returns the server's representation of the machineType, and an error, if there is any.
func (c *FakeMachineTypes) Create(ctx context.Context, machineType *v1alpha1.MachineType, opts v1.CreateOptions) (result *v1alpha1.MachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(machinetypesResource, c.ns, machineType), &v1alpha1.MachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineType), err
}

// Update takes the representation of a machineType and updates it. Returns the server's representation of the machineType, and an error, if there is any.
func (c *FakeMachineTypes) Update(ctx context.Context, machineType *v1alpha1.MachineType, opts v1.UpdateOptions) (result *v1alpha1.MachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(machinetypesResource, c.ns, machineType), &v1alpha1.MachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineType), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMachineTypes) UpdateStatus(ctx context.Context, machineType *v1alpha1.MachineType, opts v1.UpdateOptions) (*v1alpha1.MachineType, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(machinetypesResource, "status", c.ns, machineType), &v1alpha1.MachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineType), err
}

// Delete takes name of the machineType and deletes it. Returns an error if one occurs.
func (c *FakeMachineTypes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(machinetypesResource, c.ns, name), &v1alpha1.MachineType{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMachineTypes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(machinetypesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.MachineTypeList{})
	return err
}

// Patch applies the patch and returns the patched machineType.
func (c *FakeMachineTypes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.MachineType, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(machinetypesResource, c.ns, name, pt, data, subresources...), &v1alpha1.MachineType{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MachineType), err
}
